logging:
  level:
    io.pivotal: info

spring:
  jpa:
    hibernate:
      ddl-auto: auto
      
greetingLanguage: English
---
spring:
  profiles: dev
greetingLanguage: French
---
spring:
  profiles: prod
greetingLanguage: Spanish
